### ISSUE TITLE
当前版本无法启动

### ISSUE THREAD

**Issue by womeng2009** [dylan-tao/nacos-plus#15]
发布的2.2.0版本，默认application.properties启动会报错：Caused by: java.lang.IllegalArgumentException: db.num is null
配置文件，解除该行注释后，再次启动会报错：
Caused by: java.lang.IllegalStateException: No DataSource set

**Comment by dylan-tao** [comment]
> 发布的2.2.0版本，默认application.properties启动会报错：Caused by: java.lang.IllegalArgumentException: db.num is null 配置文件，解除该行注释后，再次启动会报错： Caused by: java.lang.IllegalStateException: No DataSource set
你需要配置数据库连接地址，这个和官网配置方式一样。请检查下application.properties的配置项，并阅读下本项目首页的readme，即可解决！

**Comment by dylan-tao** [comment]
> 发布的2.2.0版本，默认application.properties启动会报错：Caused by: java.lang.IllegalArgumentException: db.num is null 配置文件，解除该行注释后，再次启动会报错： Caused by: java.lang.IllegalStateException: No DataSource set

这种一般是数据库服务端版本不兼容，可以看下\nacos\logs\config-server.log或naming-server.log具体错误具体对待即可
