### ISSUE TITLE
nacos-server-2.3.2.zip 修改nacos上配置文件不生效

### ISSUE THREAD

**Issue by sleepGuo** [dylan-tao/nacos-plus#37]
修改配置之后读取的配置还是创建配置时的值，重启nacos原先配置文件读取为空 Ignore the empty nacos configuration and get it based on dataId，启动命令为：sh startup.sh -m standalone

**Comment by dylan-tao** [comment]
> 修改配置之后读取的配置还是创建配置时的值，重启nacos原先配置文件读取为空 Ignore the empty nacos configuration and get it based on dataId，启动命令为：sh startup.sh -m standalone

请下载最新版本，数据库连接配置修改了么？

**Comment by sleepGuo** [comment]
修改了，使用官方2.4版本不会出现这个问题

**Comment by dylan-tao** [comment]
> 修改了，使用官方2.4版本不会出现这个问题

用的什么数据库类型的？我验证下，应该是哪里配置错了，请提供实际配置，可以脱敏下，帮你查下问题所在。

**Comment by dylan-tao** [comment]
> 修改了，使用官方2.4版本不会出现这个问题



#### 您使用的版本？例如：2.3.2.4 | Your usage version? PS：2.3.2.4

#### 您做了什么操作？| What did you do? 

### 预期行为 | Expected behavior

### 实际行为 | Actual behavior

### 问题重现步骤 | Steps to reproduce the problem

**Comment by insiston** [comment]
不能使用，都是问题

**Comment by dylan-tao** [comment]
> 不能使用，都是问题

请下载最新版本，其他使用的都投产了
