### ISSUE TITLE
Unsatisfied dependency expressed through field namespacePersistService

### ISSUE THREAD

**Issue by clcc2019** [dylan-tao/nacos-plus#46]
<img width="1511" alt="image" src="https://github.com/dylan-tao/nacos-plus/assets/46099295/a232a1a7-7447-405c-b554-c316d2e29d27">
<img width="574" alt="image" src="https://github.com/dylan-tao/nacos-plus/assets/46099295/2d981c4b-1d53-4ec9-a7ed-8e7e0c61d7e6">

**Comment by dylan-tao** [comment]
这个问题是由于没有配置db.pool.config.driver-class-name指定数据库驱动导致的，新版本2.3.2.5版本已经修复
