### ISSUE TITLE
🙋 问题简述 使用dm数据库连接，进入nacos之后有两个接口会报500| [Question] Brief description of the problem

### ISSUE THREAD

**Issue by shangshangbaba** [dylan-tao/nacos-plus#47]
![1719887345942](https://github.com/dylan-tao/nacos-plus/assets/26432398/6c556d22-c75d-48d8-ad94-0df0fee6ef6f)

#### 您使用的版本？例如：2.3.2.4 | Your usage version? PS：2.3.2.4
ps:2.3.2.4
#### 您做了什么操作？| What did you do? 
win11

**Comment by shangshangbaba** [comment]
jdk版本的问题 ，换成jdk11后没有报错。

**Comment by dylan-tao** [comment]
ok, 按说jdk8也不会报错

**Comment by dylan-tao** [comment]
> jdk版本的问题 ，换成jdk11后没有报错。

我发布打包时应该用的jdk17版本，另一个使用者如果核实了我再用jdk8编译发布下，着急的话也可以自行在jdk8上编译打包下
