### ISSUE TITLE
🙋 问题简述 | [Question] Handler dispatch failed

### ISSUE THREAD

**Issue by clcc2019** [dylan-tao/nacos-plus#50]
#### 您使用的版本？例如：2.3.2.4 | Your usage version? PS：2.3.2.4
最新版
#### 您做了什么操作？| What did you do? 
none
### 预期行为 | Expected behavior
runing
### 实际行为 | Actual behavior
<img width="1479" alt="image" src="https://github.com/dylan-tao/nacos-plus/assets/46099295/8a63e53f-8ec6-4fe8-ab5f-2bd7b3ccd795">

**Comment by dylan-tao** [comment]
这个问题和jdk版本有关系，辛苦提供洗jdk版本是8还是11还是17？然后我检查下是不是发布包时编译的jdk版本不对

**Comment by dylan-tao** [comment]
#47 同样问题，辛苦核实后，我用jdk8再发个包看看

**Comment by dylan-tao** [comment]
> #### 您使用的版本？例如：2.3.2.4 | Your usage version? PS：2.3.2.4
> 最新版
> 
> #### 您做了什么操作？| What did you do?
> none
> 
> ### 预期行为 | Expected behavior
> runing
> 
> ### 实际行为 | Actual behavior
> <img alt="image" width="1479" src="https://private-user-images.githubusercontent.com/46099295/347671943-8a63e53f-8ec6-4fe8-ab5f-2bd7b3ccd795.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3MDgzMzYsIm5iZiI6MTcyMTcwODAzNiwicGF0aCI6Ii80NjA5OTI5NS8zNDc2NzE5NDMtOGE2M2U1M2YtOGVjNi00ZmU4LWFiNWYtMmJkN2IzY2NkNzk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIzVDA0MTM1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyN2EwMzVhYTNiZTczMDdiN2QxYThiODk1ZWJhZGZhZjVkMzVkMDk2NjRlMzZiZmE4ZDYzMTk1Njk5Y2FhNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.f_1n321BvsXmmxFSVgNRdoRFr6AWDweQbzvIlitt6gk">
> ### 问题重现步骤 | Steps to reproduce the problem

请下载2.3.2.5版本的制成品：nacos-server-2.3.2-with-jdk8.tar.gz，当前你下载的是jdk17的版本在jdk8版本上运行导致的。
