### ISSUE TITLE
Oracle脚本执行异常

### ISSUE THREAD

**Issue by Binssss** [dylan-tao/nacos-plus#54]
oracle sql 脚本存在存储过程，需要在存储过程结束后面，加一个 "/" , 然后整个SQL执行就没问题了
![image](https://github.com/user-attachments/assets/860fa14d-c839-40e2-a180-a238b52660f7)

**Comment by dylan-tao** [comment]
> oracle sql 脚本存在存储过程，需要在存储过程结束后面，加一个 "/" , 然后整个SQL执行就没问题了 ![image](https://private-user-images.githubusercontent.com/21335012/357306280-860fa14d-c839-40e2-a180-a238b52660f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMjk4NzcsIm5iZiI6MTcyNDMyOTU3NywicGF0aCI6Ii8yMTMzNTAxMi8zNTczMDYyODAtODYwZmExNGQtYzgzOS00MGUyLWExODAtYTIzOGI1MjY2MGY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDEyMjYxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3YWNjODI5ZDZlZmM4ZWE1ZWQzMTM1NzU1NGE4OTVjNGVkM2IzZGVjYjM5MjYwMTgxZGRhN2ZiOWY0YTkxYTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Mi-lcq1Dd4rXtpzA_x6z6YfE8Hb1uHWDPK6scfp63pc)

main分支已经维护，还未打包制成品
