### ISSUE TITLE
🙋  集群的配置中心读取不到配置文件

### ISSUE THREAD

**Issue by duzhan** [dylan-tao/nacos-plus#55]
在版本2.3.2.4，集群cluster配置，Oracle数据库，nacos登录、配置文件都能成功  

启动服务加载配置中心文件，找不到文件   
后面试了standalone是可以读取到文件的  

查看nacos的access日志，发现configs交易出现异常，通过postman进行测试，交易报config data not exist
![12](https://github.com/user-attachments/assets/9401940f-0be8-4e7c-b80e-2968d9271a56)

通过postman测试standalone版本时，数据可以正常返回。  
想问下是什么问题，或者配置有什么要注意的地方

**Comment by dylan-tao** [comment]
> 在版本2.3.2.4，集群cluster配置，Oracle数据库，nacos登录、配置文件都能成功
> 
> 启动服务加载配置中心文件，找不到文件 后面试了standalone是可以读取到文件的
> 
> 查看nacos的access日志，发现configs交易出现异常，通过postman进行测试，交易报config data not exist ![12](https://private-user-images.githubusercontent.com/35721007/358846143-9401940f-0be8-4e7c-b80e-2968d9271a56.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwNjY4MjUsIm5iZiI6MTcyNDA2NjUyNSwicGF0aCI6Ii8zNTcyMTAwNy8zNTg4NDYxNDMtOTQwMTk0MGYtMGJlOC00ZTdjLWI4MGUtMjk2OGQ5MjcxYTU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDExMjIwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwZjhmNzE2ODk1ODhkNjMyYzZmMmFmYTc5N2U1N2MwNGQ0Y2MxMWFjMmNjMmMxZmYxYjNjNzk2NjJiNWQ1NTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aRQHGGFPE0k63V-wLXAIqqObftHKrY4AAKopVYUrxEA)
> 
> 通过postman测试standalone版本时，数据可以正常返回。 想问下是什么问题，或者配置有什么要注意的地方

是不是在nacos上配置的文件没有命名为.properties后缀？麻烦配置文件界面也截图下，谢谢！

**Comment by duzhan** [comment]
配置文件是正常的，conf/application.properties conf/cluster.conf，这种情况是上传文件到配置中心后，服务第一次去取是没问题的，如果有修改就取不到了，也就是说修改需要删除配置中心的文件重新上传，服务也需要重启才可以，不能做到动态修改配置
