### ISSUE TITLE
oracle 12c添加配置文件失败

### ISSUE THREAD

**Issue by yangxiongwei** [dylan-tao/nacos-plus#60]
<img width="1909" alt="image" src="https://github.com/user-attachments/assets/765f8847-cf09-4c3b-86e4-84191b8fdabd">
我用的版本是
<img width="773" alt="image" src="https://github.com/user-attachments/assets/51ac62a1-5291-49fd-acdf-d0a6f37bd8cc">

**Comment by dylan-tao** [comment]
> #### 您使用的版本？例如：2.3.2.4 | Your usage version? PS：2.3.2.4
> #### 您做了什么操作？| What did you do?
> ### 预期行为 | Expecte
> ![12123](https://private-user-images.githubusercontent.com/58254653/367323591-7d2a1b67-02d2-4014-8345-b53ba1dbbdfc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyODE4OTgsIm5iZiI6MTcyNjI4MTU5OCwicGF0aCI6Ii81ODI1NDY1My8zNjczMjM1OTEtN2QyYTFiNjctMDJkMi00MDE0LTgzNDUtYjUzYmExZGJiZGZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE0VDAyMzk1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1NzE2YzA1MDc5MGMzMWNkYzlmNjFiZjM0OTMwNjg2NDYwZmY4ZmQ3M2MxNjA0NDNmYWU0ZjM0ZTBhNGJiMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oI-cXQq9QAd7dPpi5aQJbkNf3OdrQCxrMbiRMf4pb6Y) d behavior
> 
> ### 实际行为 | Actual behavior
> ### 问题重现步骤 | Steps to reproduce the problem

你这提问怎么给你解答，用的什么数据库？nacos的日志提供下？为啥用2.3.2.4而不是2.3.2.5？

**Comment by yangxiongwei** [comment]
你好，我用的版本是
<img width="773" alt="image" src="https://github.com/user-attachments/assets/d80c5971-6d25-42d0-986f-e225729419f2">

**Comment by yangxiongwei** [comment]
测试了添加服务，添加用户，添加角色，都没问题。测试到添加配置就报错了。
数据库版本是
19.23.0.0.0
Oracle Database 19c Enterprise Edition

**Comment by yangxiongwei** [comment]
感谢博主解决了，我把上面数据库版本查了一下，想起了驱动问题。
    <dependency>
        <groupId>com.oracle.ojdbc</groupId>
        <artifactId>ojdbc8</artifactId>
        <version>19.3.0.0</version>
      </dependency>
19C对应的数据库 maven也要换成对应的

**Comment by dylan-tao** [comment]
> 感谢博主解决了，我把上面数据库版本查了一下，想起了驱动问题。 ` <dependency> <groupId>com.oracle.ojdbc</groupId> <artifactId>ojdbc8</artifactId> <version>19.3.0.0</version> </dependency>` 19C对应的数据库 maven也要换成对应的

哈哈，恭喜～🎉
