### ISSUE TITLE
🙋 问题简述  升级至2.4.2 编译运行后报错

### ISSUE THREAD

**Issue by darkpara** [dylan-tao/nacos-plus#61]
#### 您使用的版本？例如：2.3.2.4 | Your usage version? PS：2.3.2.4
使用release 2.3.2.6 tag 源码编译。

#### 您做了什么操作？| What did you do? 
主pom的nacos依赖升级 2.3.2 --- 》 2.4.2

### 实际行为 | Actual behavior
编译运行后，报错。 2.3.2依赖 无问题。

### 问题重现步骤 | Steps to reproduce the problem
使用达梦数据库连接。

**Comment by dylan-tao** [comment]
> #### 您使用的版本？例如：2.3.2.4 | Your usage version? PS：2.3.2.4
> 使用release 2.3.2.6 tag 源码编译。
> 
> #### 您做了什么操作？| What did you do?
> 主pom的nacos依赖升级 2.3.2 --- 》 2.4.2
> 
> ### 预期行为 | Expected behavior
> ### 实际行为 | Actual behavior
> 编译运行后，报错。 2.3.2依赖 无问题。
> 
> ### 问题重现步骤 | Steps to reproduce the problem
> 使用达梦数据库连接。

本项目目前只维护当前最稳定的nacos版本，新版本投产风险系数过高且一定是不兼容的，需要自己clone代码适配新版本
